"use client";
import Footer from "@/components/footer/Footer"
import Navigationbar from "@/components/navbar/Navbar"
import { useEffect } from "react";
import 'bootstrap/dist/css/bootstrap.css'
import "../../styles/globals.css"
import { ReduxProvider } from "@/store/provider";
import { useSelector } from "react-redux";
import { AuthProvider } from "@/store/context/AuthContextProvider";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");

    require("flatpickr/dist/themes/airbnb.css")
  }, [])
  return (
    <html lang="en">
      <AuthProvider>
        <ReduxProvider>
          <body style={{ "height": "100vh" }}>
            <Navigationbar />
            {children}
            <Footer />
          </body>
        </ReduxProvider>
      </AuthProvider>
    </html>
  )
}
